In [12]:
import pandas as pd
import numpy as np
from pathlib import Path

In [13]:
from pathlib import Path
import pandas as pd

input_path = Path(r"D:\Suwaaq\College\Sem 5\ML\ML_2026\data\processed\olist_orders_abt.csv")

print("Resolved path:", input_path.resolve())
print("Exists:", input_path.exists())

df = pd.read_csv(input_path)

print("Shape:", df.shape)
df.head()

Resolved path: D:\Suwaaq\College\Sem 5\ML\ML_2026\data\processed\olist_orders_abt.csv
Exists: True
Shape: (99441, 29)

,order_id,customer_id,customer_unique_id,customer_city,customer_state,order_status,order_year,order_month,order_day,order_day_of_week,...,total_payment_value,max_payment_installments,payment_types_count,dominant_payment_type,total_items,total_price,total_freight,unique_products,unique_sellers,main_product_category
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,7c396fd4830fd04220f754e42b4e5bff,sao paulo,SP,delivered,2017,10,2,0,...,38.71,1.0,2.0,voucher,1.0,29.99,8.72,1.0,1.0,housewares
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,af07308b275d755c9edb36a90c618231,barreiras,BA,delivered,2018,7,24,1,...,141.46,1.0,1.0,boleto,1.0,118.70,22.76,1.0,1.0,perfumery
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,3a653a41f6f9fc3d2a113cf8398680e8,vianopolis,GO,delivered,2018,8,8,2,...,179.12,3.0,1.0,credit_card,1.0,159.90,19.22,1.0,1.0,auto
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,7c142cf63193a1473d2e66489a9ae977,sao goncalo do amarante,RN,delivered,2017,11,18,5,...,72.20,1.0,1.0,credit_card,1.0,45.00,27.20,1.0,1.0,pet_shop
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,72632f0f9dd73dfee390c9b22eb56dd6,santo andre,SP,delivered,2018,2,13,1,...,28.62,1.0,1.0,credit_card,1.0,19.90,8.72,1.0,1.0,stationery

In [14]:
target = "is_late_delivery"

In [15]:
identifier_columns = [
    "order_id",
    "customer_id",
    "customer_unique_id"
]

In [16]:
leakage_columns = [
    "delivery_days",
    "delivery_delay_days",
    "review_score",
    "review_comment_count",
    "has_review_comment",
    "is_low_review"
]

In [17]:
columns_to_drop = [
    c for c in identifier_columns + leakage_columns
    if c in df.columns
]

feature_df = df.drop(columns=columns_to_drop)

print(feature_df.columns.tolist())

['customer_city', 'customer_state', 'order_status', 'order_year', 'order_month', 'order_day', 'order_day_of_week', 'order_hour', 'estimated_delivery_days', 'is_late_delivery', 'total_payment_value', 'max_payment_installments', 'payment_types_count', 'dominant_payment_type', 'total_items', 'total_price', 'total_freight', 'unique_products', 'unique_sellers', 'main_product_category']

In [18]:
if {"total_price", "total_items"}.issubset(df.columns):
    df["average_item_price"] = (df["total_price"] / df["total_items"].replace(0, np.nan))

In [ ]:
if {"total_freight", "total_price"}.issubset(df.columns):
    df["freight_ratio"] = (
        df["total_freight"] /
        df["total_price"].replace(0, np.nan)
    )

In [20]:
if {"total_items", "unique_sellers"}.issubset(df.columns):
    df["items_per_seller"] = (
        df["total_items"] /
        df["unique_sellers"].replace(0, np.nan)
    )

In [21]:
if {"unique_sellers", "total_items"}.issubset(df.columns):
    df["seller_diversity"] = (
        df["unique_sellers"] /
        df["total_items"].replace(0, np.nan)
    )

In [22]:
if "order_day_of_week" in df.columns:
    df["is_weekend"] = (
        df["order_day_of_week"] >= 5
    ).astype(int)

In [23]:
if "order_hour" in df.columns:
    df["is_business_hour"] = (
        df["order_hour"].between(9, 18)
    ).astype(int)

In [24]:
if "order_month" in df.columns:
    df["is_year_end"] = (
        df["order_month"].isin([11, 12])
    ).astype(int)

In [25]:
if "order_month" in df.columns:
    df["month_sin"] = np.sin(
        2 * np.pi * df["order_month"] / 12
    )

    df["month_cos"] = np.cos(
        2 * np.pi * df["order_month"] / 12
    )

In [26]:
if "order_hour" in df.columns:
    df["hour_sin"] = np.sin(
        2 * np.pi * df["order_hour"] / 24
    )
    
    df["hour_cos"] = np.cos(
        2 * np.pi * df["order_hour"] / 24
    )

In [27]:
if "total_price" in df.columns:
    df["log_total_price"] = np.log1p(
        df["total_price"].clip(lower=0)
    )

if "total_freight" in df.columns:
    df["log_total_freight"] = np.log1p(
        df["total_freight"].clip(lower=0)
    )

In [28]:
if "total_price" in df.columns:
    df["price_band"] = pd.cut(
        df["total_price"],
            bins=[-np.inf, 100, 500, 1000, 5000, np.inf],
            labels=[
            "very_low",
            "low",
            "medium",
            "high",
            "very_high"
        ]
    )

In [29]:
if {"total_items", "total_price"}.issubset(df.columns):
    df["items_x_price"] = (
        df["total_items"] * df["total_price"]
    )

In [31]:
engineered_columns = [
    "average_item_price",
    "freight_ratio",
    "items_per_seller",
    "seller_diversity"
]

available_engineered = [
    c for c in engineered_columns
    if c in df.columns
]

df[available_engineered].isna().sum()

average_item_price    775
freight_ratio         775
items_per_seller      775
seller_diversity      775
dtype: int64

In [32]:
new_columns = [
    "average_item_price",
    "freight_ratio",
    "items_per_seller",
    "seller_diversity",
    "is_weekend",
    "is_business_hour",
    "is_year_end",
    "month_sin",
    "month_cos",
    "hour_sin",
    "hour_cos",
    "log_total_price",
    "log_total_freight",
    "price_band",
    "items_x_price"
]

In [33]:
new_columns = [
    c for c in new_columns
    if c in df.columns
]

df[new_columns].head()

,average_item_price,freight_ratio,items_per_seller,seller_diversity,is_weekend,is_business_hour,is_year_end,month_sin,month_cos,hour_sin,hour_cos,log_total_price,log_total_freight,price_band,items_x_price
0,29.99,0.290764,1.0,1.0,0,1,0,-0.866025,0.500000,0.500000,-0.866025,3.433665,2.274186,very_low,29.99
1,118.70,0.191744,1.0,1.0,0,0,0,-0.500000,-0.866025,-0.866025,0.500000,4.784989,3.168003,low,118.70
2,159.90,0.120200,1.0,1.0,0,0,0,-0.866025,-0.500000,0.866025,-0.500000,5.080783,3.006672,low,159.90
3,45.00,0.604444,1.0,1.0,1,0,1,-0.500000,0.866025,-0.965926,0.258819,3.828641,3.339322,very_low,45.00
4,19.90,0.438191,1.0,1.0,0,0,0,0.866025,0.500000,-0.707107,0.707107,3.039749,2.274186,very_low,19.90

In [34]:
from sklearn.feature_selection import VarianceThreshold

In [36]:
numeric_df = df.select_dtypes(
    include=np.number
).copy()

numeric_df = numeric_df.drop(
    columns=[target],
    errors="ignore"
)

selector = VarianceThreshold(threshold=0.0)

selector.fit(
    numeric_df.fillna(numeric_df.median())
)

selected_numeric = numeric_df.columns[
    selector.get_support()
]

print("Original:", len(numeric_df.columns))
print("After variance filtering:", len(selected_numeric))

Original: 34
After variance filtering: 34

In [37]:
corr = numeric_df.corr(numeric_only=True)
corr

,order_year,order_month,order_day,order_day_of_week,order_hour,delivery_days,estimated_delivery_days,delivery_delay_days,review_score,is_low_review,...,is_weekend,is_business_hour,is_year_end,month_sin,month_cos,hour_sin,hour_cos,log_total_price,log_total_freight,items_x_price
order_year,1.000000,-0.550059,-0.043672,-0.017917,-0.003229,-0.050156,-0.142717,0.067070,0.004872,0.000559,...,-0.007842,0.014861,-0.418601,0.384586,-0.239787,0.002193,-0.018217,0.002420,0.006291,-0.001697
order_month,-0.550059,1.000000,0.001343,0.020588,-0.003953,-0.054398,-0.094182,0.025640,0.027560,-0.023095,...,0.006949,-0.013991,0.653618,-0.779053,0.104784,0.005060,0.013300,0.007743,0.008077,0.002842
order_day,-0.043672,0.001343,1.000000,-0.024895,-0.012195,-0.000528,-0.030391,0.024665,0.001774,-0.001763,...,-0.012283,0.004332,0.049311,-0.007958,0.040667,0.008465,-0.005243,-0.012869,-0.006626,0.001063
order_day_of_week,-0.017917,0.020588,-0.024895,1.000000,0.009433,0.028807,0.067685,-0.031395,-0.008246,0.003517,...,0.768693,-0.020495,0.036749,-0.002184,0.021455,-0.027702,0.030770,-0.007037,0.001661,-0.004792
order_hour,-0.003229,-0.003953,-0.012195,0.009433,1.000000,-0.004758,-0.000144,0.022651,0.005765,-0.006700,...,0.043324,-0.284269,-0.002924,0.001749,-0.002273,-0.731042,0.441757,0.009325,0.004170,-0.003033
delivery_days,-0.050156,-0.054398,-0.000528,0.028807,-0.004758,1.000000,0.382836,0.607716,-0.334150,0.305947,...,0.003208,0.008565,0.110843,0.139792,0.200153,-0.004024,-0.004807,0.084508,0.252799,0.022864
estimated_delivery_days,-0.142717,-0.094182,-0.030391,0.067685,-0.000144,0.382836,1.000000,-0.499649,-0.054533,0.042413,...,0.038642,-0.004614,0.042641,0.158750,0.130545,-0.005420,0.008675,0.119597,0.369335,0.039232
delivery_delay_days,0.067070,0.025640,0.024665,-0.031395,0.022651,0.607716,-0.499649,1.000000,-0.266990,0.252709,...,-0.030329,-0.005406,0.063323,-0.001307,0.075595,-0.018859,0.010679,-0.023462,-0.082287,-0.012812
review_score,0.004872,0.027560,0.001774,-0.008246,0.005765,-0.334150,-0.054533,-0.266990,1.000000,-0.883055,...,-0.000856,0.000969,-0.037643,-0.057687,-0.077579,0.003125,-0.004266,-0.046397,-0.103214,-0.056734
is_low_review,0.000559,-0.023095,-0.001763,0.003517,-0.006700,0.305947,0.042413,0.252709,-0.883055,1.000000,...,-0.001134,-0.001281,0.033487,0.049125,0.067118,-0.001755,0.003539,0.053767,0.096209,0.057669
review_comment_count,-0.020369,-0.009445,-0.002527,-0.003897,-0.009375,0.085097,0.044501,0.042127,-0.258592,0.279705,...,-0.003711,-0.003219,-0.001282,0.010678,0.018038,0.006862,0.002646,0.050181,0.063832,0.031059
has_review_comment,-0.019840,-0.008929,-0.002751,-0.004271,-0.009162,0.084981,0.043892,0.042589,-0.259388,0.281246,...,-0.004009,-0.003050,-0.001187,0.010398,0.017682,0.006488,0.002571,0.050702,0.063973,0.031308
total_payment_value,-0.000183,0.002795,-0.008652,-0.002538,0.004185,0.069496,0.094915,-0.017743,-0.049137,0.055514,...,-0.004013,0.013845,-0.007296,-0.000972,-0.011767,-0.009448,-0.010998,0.728198,0.447608,0.662697
max_payment_installments,-0.059538,0.030311,0.001596,0.026230,0.013405,0.051852,0.094111,-0.030909,-0.031006,0.034329,...,0.028445,-0.019672,0.013966,-0.022352,-0.015839,-0.015549,0.027149,0.409233,0.244892,0.146641
payment_types_count,-0.019503,0.003532,0.002613,-0.000564,0.005917,0.001487,0.011618,-0.008432,-0.001868,-0.001024,...,-0.005315,-0.005562,0.000888,-0.003713,0.002748,0.000049,0.005410,-0.008241,0.003781,-0.006702
total_items,0.000211,0.000457,0.011453,-0.011766,-0.009770,-0.019167,0.015000,-0.031915,-0.115559,0.114780,...,-0.014956,0.017490,0.002483,0.000320,0.005730,0.003848,-0.016226,0.179343,0.397014,0.447992
total_price,-0.002716,0.001993,-0.007884,-0.002625,0.004538,0.055466,0.076126,-0.013443,-0.039724,0.046987,...,-0.003871,0.012974,-0.006680,0.000122,-0.009266,-0.009826,-0.009920,0.720951,0.385484,0.653239
total_freight,0.027865,0.003800,-0.008286,-0.002400,0.000074,0.167077,0.237994,-0.049303,-0.088623,0.085856,...,-0.000913,0.015536,-0.013705,-0.010012,-0.029304,-0.006721,-0.013398,0.400717,0.806781,0.392821
unique_products,-0.004688,0.009030,0.006638,0.004694,0.003316,-0.029999,0.022900,-0.047724,-0.097079,0.098228,...,0.005544,0.001450,0.004201,-0.010920,-0.000106,-0.007450,0.004145,0.106619,0.216180,0.146858
unique_sellers,0.017861,0.004820,0.002989,0.011540,-0.003613,-0.040664,0.023690,-0.059083,-0.107921,0.108638,...,0.013542,-0.001054,-0.004673,-0.010240,-0.011959,-0.001248,0.003597,0.077943,0.150632,0.083382
average_item_price,-0.002878,0.001007,-0.010008,-0.000244,0.007787,0.060274,0.074276,-0.006781,-0.012212,0.020426,...,0.000852,0.007479,-0.007227,0.001931,-0.010077,-0.011309,-0.004448,0.700801,0.309114,0.380720
freight_ratio,0.008289,-0.013934,0.003086,0.005708,-0.007133,0.079801,0.122061,-0.031800,-0.021031,0.012420,...,0.004003,-0.004760,-0.014485,0.006583,-0.016207,0.004621,0.002763,-0.622891,0.125915,-0.126820
items_per_seller,-0.004940,-0.001179,0.010900,-0.015406,-0.008704,-0.008434,0.009083,-0.016586,-0.091429,0.090464,...,-0.019655,0.018380,0.004025,0.003463,0.009343,0.003628,-0.017566,0.165742,0.373793,0.438938
seller_diversity,0.007314,0.001282,-0.010426,0.015248,0.008228,0.012562,-0.008877,0.020144,0.099632,-0.100549,...,0.019807,-0.016820,-0.004723,-0.004416,-0.008714,-0.002946,0.016030,-0.166725,-0.386927,-0.281993
is_weekend,-0.007842,0.006949,-0.012283,0.768693,0.043324,0.003208,0.038642,-0.030329,-0.000856,-0.001134,...,1.000000,-0.032111,0.010288,0.002830,0.007544,-0.056026,0.050203,-0.004224,0.002832,-0.009506
is_business_hour,0.014861,-0.013991,0.004332,-0.020495,-0.284269,0.008565,-0.004614,-0.005406,0.000969,-0.001281,...,-0.032111,1.000000,-0.014548,0.008392,-0.004136,0.056347,-0.855677,0.012733,0.013845,0.015248
is_year_end,-0.418601,0.653618,0.049311,0.036749,-0.002924,0.110843,0.042641,0.063323,-0.037643,0.033487,...,0.010288,-0.014548,1.000000,-0.204841,0.577583,-0.000066,0.021044,0.000797,-0.008895,-0.002779
month_sin,0.384586,-0.779053,-0.007958,-0.002184,0.001749,0.139792,0.158750,-0.001307,-0.057687,0.049125,...,0.002830,0.008392,-0.204841,1.000000,0.065935,-0.001082,-0.006815,-0.001344,-0.020341,-0.003589
month_cos,-0.239787,0.104784,0.040667,0.021455,-0.002273,0.200153,0.130545,0.075595,-0.077579,0.067118,...,0.007544,-0.004136,0.577583,0.065935,1.000000,-0.002237,0.012515,-0.004059,-0.013791,-0.001826
hour_sin,0.002193,0.005060,0.008465,-0.027702,-0.731042,-0.004024,-0.005420,-0.018859,0.003125,-0.001755,...,-0.056026,0.056347,-0.000066,-0.001082,-0.002237,1.000000,-0.327917,-0.011259,-0.010898,-0.002164
hour_cos,-0.018217,0.013300,-0.005243,0.030770,0.441757,-0.004807,0.008675,0.010679,-0.004266,0.003539,...,0.050203,-0.855677,0.021044,-0.006815,0.012515,-0.327917,1.000000,-0.010105,-0.010535,-0.013640
log_total_price,0.002420,0.007743,-0.012869,-0.007037,0.009325,0.084508,0.119597,-0.023462,-0.046397,0.053767,...,-0.004224,0.012733,0.000797,-0.001344,-0.004059,-0.011259,-0.010105,1.000000,0.464990,0.384879
log_total_freight,0.006291,0.008077,-0.006626,0.001661,0.004170,0.252799,0.369335,-0.082287,-0.103214,0.096209,...,0.002832,0.013845,-0.008895,-0.020341,-0.013791,-0.010898,-0.010535,0.464990,1.000000,0.292881
items_x_price,-0.001697,0.002842,0.001063,-0.004792,-0.003033,0.022864,0.039232,-0.012812,-0.056734,0.057669,...,-0.009506,0.015248,-0.002779,-0.003589,-0.001826,-0.002164,-0.013640,0.384879,0.292881,1.000000

In [38]:
threshold = 0.90
upper = corr.where(
    np.triu(
    np.ones(corr.shape),
    k=1
    ).astype(bool)
)

high_corr_pairs = []
for col in upper.columns:
    for row in upper.index:
        value = upper.loc[row, col]

        if pd.notna(value) and abs(value) > threshold:
            high_corr_pairs.append(
                (row, col, value)
            )
            
            high_corr_pairs[:20]

In [39]:
from sklearn.feature_selection import mutual_info_classif

In [40]:
mi_df = df.select_dtypes(
    include=np.number
).copy()

mi_df = mi_df.drop(
    columns=[target],
    errors="ignore"
)

mi_df = mi_df.fillna(
    mi_df.median()
)

mi_scores = mutual_info_classif(
    mi_df,
    df[target],
    random_state=42
)

mi_results = pd.DataFrame({
    "feature": mi_df.columns,
    "mutual_information": mi_scores
}).sort_values(
    "mutual_information",
    ascending=False
)

mi_results.head(15)

                 feature  mutual_information
7    delivery_delay_days            0.243227
5          delivery_days            0.133898
8           review_score            0.052955
9          is_low_review            0.041675
19        unique_sellers            0.027428
18       unique_products            0.023377
25      is_business_hour            0.017332
14   payment_types_count            0.016252
23      seller_diversity            0.014488
1            order_month            0.013751
11    has_review_comment            0.013281
10  review_comment_count            0.012319
28             month_cos            0.011800
22      items_per_seller            0.011279
15           total_items            0.010582

In [41]:
from sklearn.ensemble import RandomForestClassifier

In [42]:
X = df.select_dtypes(
    include=np.number
).drop(
    columns=[target],
    errors="ignore"
)

X = X.fillna(X.median())
y = df[target]

In [43]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1,
    class_weight="balanced"
)
rf.fit(X, y)

RandomForestClassifier(class_weight='balanced', n_jobs=-1, random_state=42)

In [44]:
importance = pd.DataFrame({
    "feature": X.columns,
    "importance": rf.feature_importances_
}).sort_values(
    "importance",
    ascending=False
)

importance.head(15)

                    feature  importance
7       delivery_delay_days    0.527008
5             delivery_days    0.252009
8              review_score    0.077646
9             is_low_review    0.051059
6   estimated_delivery_days    0.024140
28                month_cos    0.009838
1               order_month    0.008549
27                month_sin    0.006220
32        log_total_freight    0.005879
17            total_freight    0.005191
11       has_review_comment    0.003020
10     review_comment_count    0.002847
2                 order_day    0.002710
0                order_year    0.002493
21            freight_ratio    0.002198

In [45]:
candidate_features = [
    "total_price",
    "total_freight",
    "total_items",
    "unique_products",
    "unique_sellers",
    "order_month",
    "order_day_of_week",
    "order_hour",
    "average_item_price",
    "freight_ratio",
    "items_per_seller",
    "seller_diversity",
    "is_weekend",
    "is_business_hour",
    "month_sin",
    "month_cos",
    "hour_sin",
    "hour_cos",
    "log_total_price",
    "log_total_freight",
    "items_x_price"
]

final_features = [
    c for c in candidate_features
    if c in df.columns
]

final_df = df[
    final_features + [target]
].copy()

print("Final shape:", final_df.shape)
final_df.head()

Final shape: (99441, 22)

,total_price,total_freight,total_items,unique_products,unique_sellers,order_month,order_day_of_week,order_hour,average_item_price,freight_ratio,...,is_weekend,is_business_hour,month_sin,month_cos,hour_sin,hour_cos,log_total_price,log_total_freight,items_x_price,is_late_delivery
0,29.99,8.72,1.0,1.0,1.0,10,0,10,29.99,0.290764,...,0,1,-0.866025,0.500000,0.500000,-0.866025,3.433665,2.274186,29.99,0
1,118.70,22.76,1.0,1.0,1.0,7,1,20,118.70,0.191744,...,0,0,-0.500000,-0.866025,-0.866025,0.500000,4.784989,3.168003,118.70,0
2,159.90,19.22,1.0,1.0,1.0,8,2,8,159.90,0.120200,...,0,0,-0.866025,-0.500000,0.866025,-0.500000,5.080783,3.006672,159.90,0
3,45.00,27.20,1.0,1.0,1.0,11,5,19,45.00,0.604444,...,1,0,-0.500000,0.866025,-0.965926,0.258819,3.828641,3.339322,45.00,0
4,19.90,8.72,1.0,1.0,1.0,2,1,21,19.90,0.438191,...,0,0,0.866025,0.500000,-0.707107,0.707107,3.039749,2.274186,19.90,0

In [46]:
output_dir = Path("data/processed")
output_dir.mkdir(
    parents=True,
    exist_ok=True
)

output_path = (
    output_dir /
    "olist_orders_feature_engineered.csv"
)

final_df.to_csv(
    output_path,
    index=False
)

print("Saved to:", output_path)

Saved to: data\processed\olist_orders_feature_engineered.csv